Num1=int(input("Enter your 1st number :"))
Num2=int(input("Enter your 2nd number :"))
Num3=int(input("Enter your 3rd number :"))
print("Subtraction of 3 number is :",Num1-Num2-Num3)
print("Multiplication of 3 number is :",Num1*Num2*Num3)
print("floor Division of 3 number is :",Num1/Num2/Num3)